### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by daCyberpunk** [lotabout/CodeGenerator#12]
I asume its only for Java templates? 
We have the same problem in each language with this IDE's. The first time I've seen a negative aspect in Intelli products.

**Comment by lotabout** [comment]
Unfortunately yes. Internally it uses velocity as the template language thus could not support languages other than java.

**Comment by daCyberpunk** [comment]
the template languages for the builtin generators in PHPStorm are also using Velocity. So that shouldnt be a problem. 
Time is much more difficult. :-) 
But I really like your plugin. And if I would be fit in JAVA I would do that.

**Comment by lotabout** [comment]
Being lack of the time and the need, I have to say sorry that I won't port the plugin to other languages. But if anyone is willing to do this, I'll be glad to share the current structure of the code.

Be prepared that that the plugin is not only a wrapper of Velocity, it has to deal with other dark corners such as:
- Popup the member selection or class selection dialog for Java classes.
- Properly write the generated contents to java files, such as format the import statements.
- Provide utility functions to access fields/methods in the template.

Currently they are Java specific, not sure if the API works for other languages too.
