### ISSUE TITLE
Use default generate menu

### ISSUE THREAD

**Issue by aesy** [lotabout/CodeGenerator#4]
I really like this, thanks for putting your time into making it.

It would make it easier/faster to use if the templates were accessible from the default generate menu! It seems like that's how it works in CodeMaker, any particular reason why it was removed?

I could make a pull request for this if you'd like.

**Comment by lotabout** [comment]
@aesy It was in the "Generate Menu" in early versions, but later I thought it would better to keep the "Generate" menu clean. Later it comes to me that I will goto "Generate" menu actually all the times.

I would be great help if you could submit PR for it. Thanks in advance!
