### ISSUE TITLE
The plugin gets stuck in loading.

### ISSUE THREAD

**Issue by EzequielCamezzana92** [lotabout/CodeGenerator#6]
When I try to create a code generator Preferences>Other Settings>Code generator it just stuck saying Loading

**Comment by lotabout** [comment]
@EzequielCamezzana92 Could you please share more information?
1. Which Intellij version are you using?
2. Which version of CodeGenerator are you using? Did you upgrade from lower version?
3. Is there any error log? (You can check by click the bottom right corner icon of Intellij)
![image](https://user-images.githubusercontent.com/1527040/35025268-802186a0-fb7f-11e7-9aca-aaada9b7fa90.png)

**Comment by EzequielCamezzana92** [comment]
1.  IntelliJ IDEA 2016.3.4 / Build #IU-163.12024.16, built on January 31, 2017
2.  CodeGenerator 3.1
3.  Logs

Error MEssage:
 

> Method me/lotabout/codegenerator/ui/CodeGeneratorConfigurable.reset()V is abstract


Details:

> > Method me/lotabout/codegenerator/ui/CodeGeneratorConfigurable.reset()V is abstract
> > java.lang.AbstractMethodError: Method me/lotabout/codegenerator/ui/CodeGeneratorConfigurable.reset()V is abstract
> > 	at me.lotabout.codegenerator.ui.CodeGeneratorConfigurable.reset(CodeGeneratorConfigurable.java)
> > 	at com.intellij.openapi.options.ex.ConfigurableCardPanel.reset(ConfigurableCardPanel.java:123)
> > 	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:80)
> > 	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:65)
> > 	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
> > 	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:65)
> > 	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:70)
> > 	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:67)
> > 	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:88)
> > 	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:116)
> > 	at com.intellij.ui.CardLayoutPanel.b(CardLayoutPanel.java:132)
> > 	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
> > 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
> > 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
> > 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> > 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> > 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> > 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> > 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> > 	at java.security.AccessController.doPrivileged(Native Method)
> > 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> > 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> > 	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
> > 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
> > 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
> > 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> > 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> > 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> > 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
> > 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
> > 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
> > 	at java.security.AccessController.doPrivileged(Native Method)
> > 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
> > 	at java.awt.Dialog.show(Dialog.java:1084)
> > 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:779)
> > 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:457)
> > 	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1693)
> > 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
> > 	at com.intellij.openapi.options.newEditor.SettingsDialog.b(SettingsDialog.java:80)
> > 	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
> > 	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:294)
> > 	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:79)
> > 	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
> > 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:159)
> > 	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:78)
> > 	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:91)
> > 	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
> > 	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:131)
> > 	at com.intellij.ide.MacOSApplicationProvider$Worker.b(MacOSApplicationProvider.java:225)
> > 	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
> > 	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
> > 	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:76)
> > 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
> > 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
> > 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> > 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> > 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> > 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> > 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> > 	at java.security.AccessController.doPrivileged(Native Method)
> > 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> > 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> > 	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
> > 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
> > 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
> > 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> > 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> > 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> > 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> > 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> > 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> > 
> 
>

**Comment by lotabout** [comment]
@EzequielCamezzana92 I reproduced this problem on idea-IU-2016.3.7.
And very sorry that I found incompatibility of Code-Generator (it was built on idea-IU-2017). Some API had changed in newer version.

I'll try to fix it to be compatible with 2016. Meanwhile if you really need this plugin, please try to use idea 2017 (community version should also work).

**Comment by lotabout** [comment]
Please checkout [Code-Genenrator-1.3.2](https://github.com/lotabout/CodeGenerator/releases/tag/v1.3.2). The Intellij plugin repository will update in a few days.
